services:
    jobboard.announcementupdate.listener:
        class: SensioLabs\JobBoardBundle\Listener\AnnouncementUpdateNotificationListener
        tags:
            - { name: doctrine.event_listener, event: preUpdate }
        calls:
            - [ setMailer, [ @mailer ] ]
            - [ setRouter, [ @router ] ]