services:
    jobboard.announcementupdate.listener:
        class: SensioLabs\JobBoardBundle\Listener\AnnouncementUpdateNotificationListener
        tags:
            - { name: doctrine.event_listener, event: preUpdate }
        arguments: [@service_container]

    jobboard.viewscount.listener:
        class: SensioLabs\JobBoardBundle\Listener\ViewsCountListener
        tags:
            - { name: doctrine.event_listener, event: postLoad }
