<?php

namespace SensioLabs\JobBoardBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\HttpFoundation\Request;

/**
 * AnnouncementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnouncementRepository extends EntityRepository
{
    public function filterAll($filters, $page, $limit = 10) {

        $qb = $this->createQueryBuilder('a');

        if(isset($filters['country'])) {
            $qb->andWhere($qb->expr()->eq('a.country', ':country'))
                ->setParameter('country', $filters['country']);
        }

        if(isset($filters['contractType'])) {
            $qb->andWhere($qb->expr()->eq('a.contractType', ':contracttype'))
                ->setParameter('contracttype', $filters['contractType']);
        }

        $qb->setFirstResult($limit*($page-1));
        $qb->setMaxResults($limit);

        return $qb->getQuery()->getResult();
    }

    public function getCountriesCount(){
        $qb = $this->createQueryBuilder('a');

        $qb->select('a.country as name, COUNT(a.id) as nb_entities')
            ->groupBy('a.country');

        return $qb->getQuery()->getArrayResult();
    }

    public function getContractTypesCount(){
        $qb = $this->createQueryBuilder('a');

        $qb->select('a.contractType as name, COUNT(a.id) as nb_entities')
            ->groupBy('a.contractType');

        return $qb->getQuery()->getArrayResult();
    }
}
